"""index transactions ledger date

Revision ID: b04aefae9719
Revises: 99cdf51e672d
Create Date: 2026-08-12 10:04:10.287580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b04aefae9719'
down_revision: Union[str, None] = '99cdf51e672d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transactions_ledger_date', 'transactions', ['ledger_id', 'transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_ledger_date', table_name='transactions')
    # ### end Alembic commands ###
